// <auto-generated />
namespace ASample.Permission.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initPermission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initPermission));
        
        string IMigrationMetadata.Id
        {
            get { return "201810291414394_initPermission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
